language: ruby
bundler_args: --without development
env:
  - USE_OFFICIAL_GEM_SOURCE=1

services:
  - redis-server

matrix:
  allow_failures:
    - rvm: ruby-head

rvm:
  - 2.0.0

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:seed --trace
  - RAILS_ENV=test bundle exec rspec -fd spec/controllers spec/helpers spec/models

before_script:
  - cp config/settings.yml.sample config/settings.yml
  - cp config/database.yml.sample config/database.yml
  - cp config/sensitive.yml.sample config/sensitive.yml
  postgresql -e 'create database IF NOT EXISTS `RubyMe_test`'
