
site_name: BlogMe
site_name_zh: BlogMe
site_ip: XXXXXXXXX
site_domain: XXXXXXXXXX

site_mailer:
  address: smtp.163.com
  user_name: zyj163loveher@163.com
  password: jason522

cdn:
  storage: qiniu
  dir_prefix: pro
  access_key: ceWhcPCdPLerb13I_cFdVlVDJB7wq3GqnIBO-UiE
  secret_key: gRQbgK_oX_ZWGrXH_VBX6OIxCfxhUfNtYa98_oTY
  bucket: jasonblog
  bucket_domain: jasonblog.qiniudn.com


exclusions:
  - www
  - admin
  - system
  - guest
  - frontend
  - backend
  - status
  - api

devise:
  secret_key: xxx

SECRET_KEY_BASE: xxx
